# Generated by Django 3.2.5 on 2021-08-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id_user', models.CharField(max_length=10)),
                ('lobby', models.CharField(max_length=100)),
            ],
        ),
    ]
