# Generated by Django 3.2.5 on 2021-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0002_players_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='play',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
