# Generated by Django 3.2.5 on 2021-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0003_players_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='root',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
