# Generated by Django 3.2.5 on 2021-08-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('bunker', '0005_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
