# Generated by Django 3.2.5 on 2021-08-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0007_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='lobby',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
