# Generated by Django 3.2.5 on 2021-08-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0008_specifications_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='play',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='root',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='open',
            field=models.BooleanField(),
        ),
    ]
