# Generated by Django 3.2.5 on 2021-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0011_players_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bunker_kata',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='bunker_pop',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='bunker_size',
            field=models.CharField(default=231, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='bunker_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
