# Generated by Django 3.2.5 on 2021-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunker', '0012_auto_20210817_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bunker_kata',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bunker_pop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bunker_size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bunker_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
