# Generated by Django 3.2.5 on 2021-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0002_alter_games_roundend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='Team',
            new_name='team',
        ),
        migrations.AddField(
            model_name='words',
            name='status',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
