# Generated by Django 3.2.5 on 2021-07-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0003_auto_20210726_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Lobbys',
        ),
    ]
